### ISSUE TITLE
unable to deploy in heroku [NodeJS Version]

### ISSUE THREAD

**Issue by thatsenam** [pdfernhout/narrafirma#31]
Error 

 NarraFirma@1.4.1 start /app
2019-10-02T08:27:45.508257+00:00 app[web.1]: > cd server && npm start
2019-10-02T08:27:45.508259+00:00 app[web.1]: 
2019-10-02T08:27:45.986538+00:00 app[web.1]: 
2019-10-02T08:27:45.986575+00:00 app[web.1]: > server@1.0.0 start /app/server
2019-10-02T08:27:45.986577+00:00 app[web.1]: > node NarraFirmaServer.js
2019-10-02T08:27:45.986579+00:00 app[web.1]: 
2019-10-02T08:27:46.240624+00:00 app[web.1]: readSuperuserInformation ./superuserInformation.json
2019-10-02T08:27:46.246235+00:00 app[web.1]: ERROR: Problem reading superuser information from file ./superuserInformation.json { Error: ENOENT: no such file or directory, open './superuserInformation.json'
2019-10-02T08:27:46.24624+00:00 app[web.1]:     at Object.openSync (fs.js:443:3)
2019-10-02T08:27:46.246243+00:00 app[web.1]:     at Object.readFileSync (fs.js:343:35)
2019-10-02T08:27:46.246245+00:00 app[web.1]:     at readSuperuserInformation (/app/server/pointrel20150417/pointrelAccessControl.js:79:27)
2019-10-02T08:27:46.246247+00:00 app[web.1]:     at Object.initialize (/app/server/pointrel20150417/pointrelAccessControl.js:64:9)
2019-10-02T08:27:46.24625+00:00 app[web.1]:     at Object.<anonymous> (/app/server/NarraFirmaServer.js:32:23)
2019-10-02T08:27:46.246252+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2019-10-02T08:27:46.246254+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-10-02T08:27:46.246256+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-10-02T08:27:46.246258+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-10-02T08:27:46.246261+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-10-02T08:27:46.246263+00:00 app[web.1]:   errno: -2,
2019-10-02T08:27:46.246266+00:00 app[web.1]:   syscall: 'open',
2019-10-02T08:27:46.246268+00:00 app[web.1]:   code: 'ENOENT',
2019-10-02T08:27:46.24627+00:00 app[web.1]:   path: './superuserInformation.json' }

**Comment by cfkurtz** [comment]
I'm sorry for not getting to this sooner. Everybody: if we do not respond to an issue quickly, please send a reminder email to cfkurtz at cfkurtz dot com.

This error happened because you did not set a superuser password. You need to do that via a command-line argument. See the instructions in "README-NodeJS.txt" specifically step 4. You will need to access the heroku command-line interface (CLI). Hope that helps.
